//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DictTermUser.h
//  @ Date : 2014/5/17
//  @ Author : 
//
//


#if !defined(_DICTTERMUSER_H)
#define _DICTTERMUSER_H

#include "DictTerm.h"

// save session & ctx related terms.
// might be transferred via web.
class DictTermUser : public DictTerm {
public:
	string DumpAsJSON();
	int LoadFromJSON(string s);
};

#endif  //_DICTTERMUSER_H
