//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DictTerm.h
//  @ Date : 2014/5/17
//  @ Author : 
//
//


#if !defined(_DICTTERM_H)
#define _DICTTERM_H

#include "DictBase.h"

class DictTerm : public DictBase {
public:
	void GetTermID(string term);
};

#endif  //_DICTTERM_H
